 f = mtk('figure', 0, '0x0', ...
             'Name', 'MTk Demo: Tab Panel', ...
             'Resize', 'off', ...
             'Visible', 'off');

     mtk('render', f, ...
         {'vbox' ...
          'Margin' 16 ...
          'Padding' 16 ...
          {'tabs' ...
           {'tab' ...
            'Caption' 'First' ...
            {'vbox' ...
             'Margin' 8 ...
             {'text' ...
              'String' 'Hello world!'}}} ...
           {'tab' ...
            'Caption' 'Second' ...
            {'vbox' ...
             'Margin' 8 ...
             {'text' ...
              'String' 'Good by sailor!'}}} ...
           {'tab' ...
            'Caption' 'Third' ...
            {'box' ...
             'Margin' 8 ...
             {'tabs' ...
              {'tab' ...
               'Caption' 'Fourth' ...
               {'vbox' ...
                'Margin' 8 ...
                {'group' ...
                 'Caption' 'Fruits:' ...
                 {'vbox' ...
                  'Margin' 8 ...
                  {'checkbox' ...
                   'String' 'Apples'} ...
                  {'checkbox' ...
                   'String' 'Bananas'}}}}} ...
              {'tab' ...
               'Caption' 'Fifth' ...
               {'vbox' ...
                'Margin' 8 ...
                {'text' ...
                 'String' 'The end.'}}}}}}} ...
          {'hbox' ...
           'Pack' 'center' ...
           {'pushbutton' ...
            'String' 'Close' ...
            'Callback' 'delete(gcbf);'}}});

     set(f, 'Visible', 'on');