%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Malu/Dropbox/BeamsModelation/System/SupportFiles/150317_I/SLM2y_transition_160317.xls
%    Worksheet: lvtemporary_915583
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/03/16 12:21:53

clear variables;close all

%% Import the data
[~, ~, raw] = xlsread('/Users/Malu/Dropbox/BeamsModelation/System/SupportFiles/150317_I/SLM2y_transition_160317.xls','lvtemporary_915583');
raw = raw(2:end,:);

%% Create output variable
data = sortrows(reshape([raw{:}],size(raw)));

%% Allocate imported array to column variable names
X_pos  = data(:,1);
Energy = data(:,2);
N      = size(data,1);

aux        = X_pos(1);
Energy_new = 0;
Nmean      = 0;
count      = 1;
for i=1:N
    
    if X_pos(i)==aux
        
        Energy_new = Energy_new + Energy(i);
        Nmean      = Nmean + 1;
        
        if i==N
             Ener_mean(count)  = Energy_new / Nmean;
             X_new(count)      = aux;  
        end
        
    else
        
        Ener_mean(count)  = Energy_new / Nmean;
        X_new(count)      = aux;
        aux               = X_pos(i);
        Energy_new        = Energy(i);
        count             = count + 1;
        Nmean             = 1;
        
    end
    
end

figure
plot(X_new,Ener_mean,'.')






